### ISSUE TITLE
Set financial goals

### ISSUE THREAD

**Issue by ama1020** [ama1020/GESPRO_PracticaGestionTareas#31]

**Comment by cmo1004** [comment]
Metas @ama1020  y @mariohu2001:
- [1] Buena inversión durante el mes de Noviembre.
- [2] Ganar un 26,7% de beneficios.
- [3] Realizar acuerdo con empresa inversora.

**Comment by mariohu2001** [comment]
He encontrado una empresa que está dispuesta a invertir en nuestro proyecto. Contactaré con ella para llegar a un acuerdo.
